package com.example.bmi.model.repositori

import com.example.bmi.PAROLGENERATOR
import com.example.bmi.R
import com.example.bmi.model.AsosiyModel
import com.example.bmi.model.QoshimchaModel
import com.example.bmi.model.QuestionModel
import java.security.SecureRandom

class Repositori {

    val arrayTest:ArrayList<QuestionModel> = arrayListOf(
        QuestionModel("Kiberxavfsizlik nima?", "Kompyuter dasturlarini o'rganish", "Tarmoq xavfsizligini ta'minlash","Internetdan foydalanish", "Elektron pochta yuborish","Tarmoq xavfsizligini ta'minlash"),
        QuestionModel("Ma'lumotlarni shifrlash nima uchun foydalaniladi?","Ma'lumotlarni yirik tarmoqdagi serverlarda saqlash uchun", "Ma'lumotlarni nazorat qilish uchun"," Ma'lumotlarni o'chirish uchun","Ma'lumotlarni xavfsiz saqlash uchun","Ma'lumotlarni xavfsiz saqlash uchun"),
        QuestionModel("Wireshark qanday imkoniyatlar beradi?"," Tarmoq xavfsizligini ta'minlash","Tarmoqdagi trafikni analiz qilish","Foydalanuvchilarni identifikatsiya qilish","Ma'lumotlarni shifrlash","Tarmoqdagi trafikni analiz qilish"),
        QuestionModel("Antivirus dasturi nima uchun ishlatiladi?"," Tarmoq xavfsizligini ta'minlash uchun","Ma'lumotlarni nazorat qilish uchun","Viruslarni aniqlash va o'chirish uchun","Ma'lumotlarni shifrlash uchun","Viruslarni aniqlash va o'chirish uchun"),
        QuestionModel("TrueCrypt nima uchun foydalaniladi?", "Tarmoq xavfsizligini ta'minlash uchun", "Ma'lumotlarni o'chirish uchun","Fayllarni shifrlash uchun","Viruslarni aniqlash va o'chirish uchun", "Ma'lumotlarni o'chirish uchun"),
        QuestionModel("Nmap qanday imkoniyatlar beradi?","Tarmoq xavfsizligini ta'minlash","Tarmoqdagi trafikni analiz qilish","Tuzilishlarni skan qilish va ma'lumot to'plash","Ma'lumotlarni shifrlash","Tuzilishlarni skan qilish va ma'lumot to'plash"),
        QuestionModel("ClamAV qanday maqsadlar uchun ishlatiladi?", "Fayllarni shifrlash","Tarmoq xavfsizligini ta'minlash","Viruslarni aniqlash va o'chirish","Tarmoq xavfsizligi tekshiruvi va pen-test qilish","Viruslarni aniqlash va o'chirish"),
        QuestionModel("Snort nima uchun foydalaniladi?", "Tarmoq xavfsizligi tekshiruvi va pen-test qilish","Tuzilishni skan qilish va ma'lumot to'plash","Fayllarni shifrlash", "Tarmoq xavfsizligini ta'minlash","Tarmoq xavfsizligi tekshiruvi va pen-test qilish"),
        QuestionModel("Wireshark nima uchun foydalaniladi?", "Viruslarni aniqlash va o'chirish","Tarmoq xavfsizligi tekshiruvi va pen-test qilish","Tuzilishni skan qilish va ma'lumot to'plash","Tarmoq xavfsizligini ta'minlash","Tarmoq xavfsizligi tekshiruvi va pen-test qilish"),
        QuestionModel("Metasploit nima uchun ishlatiladi?", "Tarmoq xavfsizligini ta'minlash uchun", "Tarmoqdagi trafikni analiz qilish uchun","Ma'lumotlarni shifrlash uchun","Tarmoq xavfsizligini tekshirish va pen-test qilish uchun","Tarmoq xavfsizligini tekshirish va pen-test qilish uchun"),
    )

    fun generatePassword(length: Int, complexity: Int) {
        val random = SecureRandom()
        val lowercase = "abcdefghijklmnopqrstuvwxyz"
        val uppercase = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
        val digits = "0123456789"
        val specialChars = "!@#$%^&*()_-+=[]{}|;:,.<>?/~"

        var password = ""

        val chars = when (complexity) {
            1 -> lowercase + uppercase + digits
            2 -> lowercase + uppercase + digits + specialChars
            else -> lowercase + uppercase + digits + specialChars + specialChars
        }

        for (i in 0 until length) {
            password += chars[random.nextInt(chars.length)]
        }
        PAROLGENERATOR.save(password)
    }

    val arrayasosiy:ArrayList<AsosiyModel> = arrayListOf(
        AsosiyModel(R.drawable.tushunchalar, "Asosiy tushunchalarni o'rganing", "9 ta dars"),
        AsosiyModel(R.drawable.qoidalar2, "Kiberxavfsizlikning asosiy qoidalari", "10 ta dars"),
        AsosiyModel(R.drawable.malumotlar, "Ma'lumotli dasturlarni o'rganish", "6 ta dars"),
        AsosiyModel(R.drawable.amalyot, "Amaliyot", "Salom"),
        AsosiyModel(R.drawable.testing, "Test", "O'zinggizni sinab ko'ring"),
        AsosiyModel(R.drawable.password, "Password", "Password Generator"),
    )

    val arraytushuncha:ArrayList<QoshimchaModel> = arrayListOf(
        QoshimchaModel(R.drawable.tushunchalar, "Kiberxavfsizlikning tarixi va rivojlanishi", "Kiberxavfsizlikning tarixi oldingi yillarda shu sohaga qaratilgan e'tibor yuzaga kelish bilan boshlandi. 1960-yillarda kompyuterlar paydo bo'lgan va ularning o'rni, internet ishlab chiqarilishiga katta imkoniyat yaratdi. 1980-yillarda birinchi dasturiy tarmoq xavfsizligi hujjatlari qabul qilindi, ammo kiberxavfsizlik haqida o'ylangan narsalar faqat odatda bir nechta insonlar o'rtasida maslahatlashilgan edi.\n" +
                "1990-yillarda internet ommalasining ko'payishi bilan birga, kiberxavfsizlik ham kattalashtirildi. Bu davrda, dasturiy tarmoqlar yuqori darajada xavfsizlikka ega bo'lmagan edi va yagona qo'llanuvchi nomzodligi, ushbu xavfsizlik muammolarini bartaraf qilish uchun zarur bo'lgan muammolar. 2000-yillarda, kompyuterlarning sonining ko'payishi va bir nechta muhim viruslar va kiber-hujumlar, xususan, \"I Love You\" virusi, \"Code Red\" va \"Nimda\" hujumlariga ko'ra, kiberxavfsizlik ham yuqori darajada e'tibor qaratildi.\n" +
                "Bugungi kunda, kiberxavfsizlik, tijoraviy, huquqiy va siyosiy masalalar kabi ko'plab ko'rsatkichlarga asoslangan, yuqori darajali tahlil va yechimlarni o'z ichiga olgan katta tizimli ish. Kiberxavfsizlik bo'yicha yangiliklar kuzatiladigan va kiberxavfsizlikning yangi yo'nalishlarini kuzatuvchi aloqa jadal suriladi. Kiberxavfsizlikning rivojlanishi esa tez va odatda o'zgaruvchan bo'lgan soha."),
        QoshimchaModel(R.drawable.tushunchalar, "Ma'lumotlar xavfsizligi", "Ma'lumotlar xavfsizligi, ma'lumotlarni qurilish, saqlash, uzatish va qo'llashish jarayonlarida himoya qilish tizimi va usullari to'plamidir. Bu himoya qilish tizimi va usullari ma'lumotlarni o'z ichiga olish, o'zgarishlarni nazorat qilish, muhofaza qilish va taqdim etishning ko'p qatlamli bo'limlaridan iboratdir.\nMa'lumotlar xavfsizligi hozirgi zamonning asosiy muddatlari va bizning qaror" +
                "qabiliyatimizning muhim qismlaridan biridir. Kompyuterlar, smartfonlar, tabletlar va boshqa qurilmalar o'ziga xos xavfsizlik muammolari bilan qarshi yuzaga keladi. Ijtimoiy tarmoq, internet tarmoqining keng rivojlanishi va undan foydalanuvchilar sonining kattalashishi, shaxsiy ma'lumotlarga qo'shimcha muhtojlik yaratdi.\nMa'lumotlar xavfsizligi tizimining barcha taraflari, ma'lumotlarni noma'lum odamlardan va shaxsiy ma'lumotlarni kiritishni yoki olishni ta'qiqlaydi. Bu tizimlar ma'lumotlarni qayta ishlab " +
                "chiqish, saqlash va tarqatish uchun himoya qilishni o'z ichiga oladi. Ma'lumotlar xavfsizligi tizimi barcha foydalanuvchilarga xavfsizligi ta'minlash uchun xavfsizlik protokollari va asosiy xavfsizlik amallari bilan ta'minlanadi."),
        QoshimchaModel(R.drawable.tushunchalar, "Malware va viruslar", "Malware (zararli dasturlar) va viruslar, kompyuter tizimlariga xavfsizlik xavfli dasturlardan tashkil topgan bir qator zararli programmalardir. Bu zararli dasturlar kompyuter tarmoqiga kirib o'tish orqali tizimni nazorat qilish, o'zgarishlarni kiritish, shaxsiy ma'lumotlarga kirish qilish va boshqa xavfli amallarni amalga oshirishga qodir.\n" +
                "Viruslar bir dastur turi bo'lib, foydalanuvchi fikrimizda olmaydigan bir qator yordamni amalga oshirish orqali o'zaro aloqani nazorat qiladi. Viruslar kompyuter tarmog'ining xavfsizligini buzish orqali tarmoqni xavfli holatga o'tkazishga qodir. Bu zararli dasturlar, kompyuter tarmoqida shaxsiy ma'lumotlarni to'plash, kompyuterni nazorat qilish va o'zgarishlarni kiritish uchun foydalaniladi.\n" +
                "Malwarelar, viruslarga qaraganda keng tarqalgan bir dasturlar to'plami hisoblanadi va foydalanuvchining talablariga qarab faollashtiriladi. Bu zararli dasturlar, tizimning xavfsizligini buzish, kompyuter tarmoqiga kirishni ta'minlash, shaxsiy ma'lumotlarni olish va boshqa xavfli amallarni amalga oshirishni qodir. Malwarelar spyware, adware, ransomware va boshqa dasturlar ko'rinishida bo'lishi mumkin.\n" +
                "Spyware (espiyonlik dasturlari), foydalanuvchining fikrini bilmadan kompyuter tarmog'ida jamiyat tizimiga kirib o'tish uchun ma'lumot to'plash uchun foydalaniladi. Adware (reklama dasturlari), foydalanuvchining tarixini va ko'rishgan narsalarni yodlash uchun kompyuter tarmog'iga kiritiladi. Ransomware, kompyuter tarmoqining ma'lumotlarni to'plashga qodir va ularni tasodifiy holatda saqlab qolishga vaqt nazoratini taqdim etishga majbur qilish uchun foydalaniladi.\n" +
                "Kiberxavfsizlikning asosiy tuzilishlari va xavfsizlikning asosiy ko'nikmalari bilan xavfsizlikni ta'minlashda, viruslar va malwarelar kabi zararli dasturlar bilan kurashish va ularni oldini olish katta muhim ahamiyatga ega."),
        QoshimchaModel(R.drawable.tushunchalar, "Hacking va cracking", "Hacking va cracking, bir-biridan farqli dasturlarni tahrirlash va xavfsizlikni buzishning bir xil usullaridir.\n" +
                "Hacking, bir tizimga o'zaro aloqani buzish yoki o'zgartirishga to'g'ridan-to'g'ri intilishni anglatadi. Hakerlar, qonuniy yoki rasmga solgan sohada yo'qotish orqali tarmoqni buzishga harakat qilishadi. Hakerlar, tizimni buzish va uni nazorat qilish uchun qulay bo'lgan dasturlar va vositalardan foydalanishadi. Hakerlar, tarmoqda o'zgartirishlar kiritish, shaxsiy ma'lumotlarga kirish qilish, hujjatlar va dokumentlar olish va boshqa xavfli amallarni amalga oshirish uchun foydalaniladi.\n" +
                "Cracking, hackingning bir turidir va bu dasturlarning asosiy maqsadi, tarmoq va dastur ni nazorat qilish uchun parolni buzishdir. Bu dasturlar, tarmoqning xavfsizligini buzish, parolni buzish va tizimni nazorat qilishga qodir. Crackerlar, parolni buzish uchun kuchli matematik algoritmlaridan foydalanishadi.\n" +
                "Hacking va cracking, xavfsizlikni buzish uchun foydalaniladi. Bu zararli amallar, shaxsiy ma'lumotlarni olish, tizimni nazorat qilish va o'zgartirish, tarmoqni buzish va boshqa xavfli amallarni amalga oshirishni qodir. Buning natijasida, zararli faoliyatlar bilan ta'sir qilingan foydalanuvchilar, kompyuter tarmog'ining xavfsizligi buziladi va shaxsiy ma'lumotlari o'zaro almashishni nazorat qilish uchun qo'lga kirishishadi."),
        QoshimchaModel(R.drawable.tushunchalar, "Kiberxavfsizlik tizimlari", "Kiberxavfsizlik tizimlari, kompyuter tarmog'ining xavfsizligini ta'minlash uchun o'rnatilgan dasturlardir. Bu tizimlar, zararli dasturlarni aniqlash, tarmoqdagi xavfli narsalarni tahlil qilish, shaxsiy ma'lumotlarni muhofaza qilish, tarmoqdagi xavfli amallarni nazorat qilish va boshqa xavfli tarmoq amallarini aniqlashga xizmat qiladi.\n" +
                "Kiberxavfsizlik tizimlari, tarmoqni xavfsizligi buzilganida foydalanuvchilarga ogohlantirish beradi. Bu tizimlar, qayta tayyorlash uchun yuklab olish, tarmoqdagi zararli dasturlarni aniqlash uchun qo'llanishadi, faqat kiberxavfsizlik tizimlarini o'rnatish o'ziga has xossalarga ega bo'lishi kerak, chunki har bir tarmoq turli xavfli amallarga dalolat beradi. Tarmoqdagi xavfli narsalarni aniqlash, faqat kiberxavfsizlik tizimlarining turli xavfli tahlil usullari va yozuvlaridan foydalanish bilan amalga oshiriladi.\n" +
                "Kiberxavfsizlik tizimlari, shaxsiy ma'lumotlarni muhofaza qilish uchun maxsus kafolatlar taqdim etadi. Bu tizimlar, foydalanuvchilarning shaxsiy ma'lumotlari o'zaro almashishini nazorat qilish, yopiq tarmoq aloqalarini yaxshi xavfsizlikda saqlash, kuchli parollar yaratish va boshqa xavfli amallarni nazorat qilish uchun yaratilgan vositalardan foydalanishadi.\n" +
                "Kiberxavfsizlik tizimlari, tarmoqdagi xavfli amallarni nazorat qilish uchun turli xil usullardan foydalanadi. Bu tizimlar, tarmoqdagi barcha amallarni kuzatish, foydalanuvchilarning kirishlari va tizimdan chiqishlari bilan bog'liq ma'lumotlar, tarmoqdagi kuchli nuktalar va ko'p yoki kam yozilgan tarmoq xabarlarini nazorat qilish va boshqa tahlil usullaridan foydalanishadi.\n" +
                "Kiberxavfsizlik tizimlari, tarmoqdagi xavfli amallarni aniqlash va ularni to'g'ridan-to'g'ri oldirishda katta yordam beradi. Bu tizimlar, zararli dasturlarni aniqlash, tarmoqni buzish va o'zgartirish"),
        QoshimchaModel(R.drawable.tushunchalar, "Tarmoq xavfsizligi", "Tarmoq xavfsizligi, kompyuter tarmog'ining xavfsizligini ta'minlashga qaratilgan turli xil chora-tadbirlar to'g'risidagi tushunchadir. Tarmoq xavfsizligi, tarmoqdagi tizimlarning, xizmatlarining va foydalanuvchilarning xavfsizligini ta'minlashga yordam beradi.\n" +
                "Tarmoq xavfsizligi, tarmoqdagi xavfli narsalarni aniqlash va tahlil qilish, zararli tizimlarni aniqlash, shaxsiy ma'lumotlarni muhofaza qilish, tarmoqdagi xavfli amallarni nazorat qilish, tarmoq xavfsizligini ta'minlash uchun keng turli chora-tadbirlar to'g'risidagi tushunchalar va tahlil usullarini o'z ichiga oladi.\n" +
                "Tarmoq xavfsizligi qo'llanish tartibi, tarmoqdagi xavfli amallarni aniqlash, tahlil qilish va oldirish, shaxsiy ma'lumotlarni muhofaza qilish va boshqa turli xavfli amallarni nazorat qilish kabi turli xil chora-tadbirlardan iborat bo'lishi mumkin. Tarmoq xavfsizligi, tarmoqni xavfsizlik bilan bog'liq turli xil to'lovchi dasturlar, yozuvlar, tarmoqdagi tizimlarning yangiligi, tarmoqdagi ulkan xavfli narsalarga qarshi xavfsizlik jihatidan muhofaza qilish, tarmoqdagi xavfli tahlil usullari, shaxsiy ma'lumotlarni muhofaza qilish uchun yaratilgan maxsus vositalar va hokazo orqali amalga oshiriladi.\n" +
                "Tarmoq xavfsizligi, internet tarmoqining keng o'zaro ulanishi va ko'plab zararli xavfli amallar va tizimlar uchun potentsial topishmaydi. Ushbu sababli, tarmoq xavfsizligi hozirgi va kelajakdagi tarmoqlar uchun juda muhimdir, chunki foydalanuvchilar shaxsiy ma'lumotlari va boshqa xavfli ma'lumotlar yoki resurslarga kirishga urinishadi."),
        QoshimchaModel(R.drawable.tushunchalar, "Fizikaviy xavfsizlik", "Fizikaviy xavfsizlik, tarmoqdagi ma'lumotlarga fizikaviy ravishda kirishga harakat qilishdan, tarmoqdagi qurilishlar va qurilmalar yoki ularning ta'mir qilinishi bilan bog'liq xavfli ma'lumotlarga ta'sir ko'rsatishdan qochishga qaratilgan turli xil chora-tadbirlar to'g'risidagi tushunchadir.\n" +
                "Fizikaviy xavfsizlik, asosan qurilishlarning va ta'sirli vositalarning qurilishi bilan bog'liqdir. Ushbu vositalarning yaqinidan o'tkazilgan bir nechta ta'mirlash va o'rnatish harakatlaridan so'ng xavfli holatlar sodir bo'lishi mumkin. Misol uchun, shaxsiy kompyuter yoki server xonasiga kirib uni ushlab turish, xavfli qurilmalarga o'rnatilgan xavfsizlikning buzilishiga olib kelishi mumkin.\n" +
                "Fizikaviy xavfsizlik, tarmoqdagi fizikaviy qurilishlarning qulayliklarini tahlil qilish, tarmoqdagi xavfli amallarni nazorat qilish, tarmoq xavfsizligini ta'minlash uchun chora-tadbirlar to'g'risida tushunchalar va usullar o'z ichiga oladi.\n" +
                "Fizikaviy xavfsizlik, tarmoq va tizimlardagi fizikaviy qurilishlarning kuchli parol yoki xavfsizlikli qurilishlar bilan ta'minlanishini o'z ichiga oladi. Tarmoqdagi ma'lumotlarni fizikaviy ravishda ta'sir ko'rsatish uchun qurilishlarni fizikaviy ravishda muhofaza qilish uchun ajratilgan bo'shliqlar, muhimiyatli ma'lumotlarni saqlash uchun yaratilgan maxsus qurilishlar, xavfli qurilishlarga o'rnatilgan xavfsizlik qurilmalari, tarmoq zonasi boyicha qurilgan qurilishlar va hokazo orqali amalga oshiriladi.\n" +
                "Bundan tashqari, fizikaviy xavfsizlik, tarmoqdagi qurilishlar va vositalarning holatlarini nazorat qilish, zararli xavfli amallar va tizimlar uchun to'g'ri jarayonlarni amalga oshirish, ushbu xavfli amallar va tizimlar uchun zararli xususiyatlarni aniqlash uchun xususiy vositalarni o'z ichiga oladi."),
        QoshimchaModel(R.drawable.tushunchalar, "Kiberxavfsizlikning huquqiy, siyosiy va tijoraviy asoslar", "Kiberxavfsizlik, yani internet va tarmoq xavfsizligi, bugungi kunda huquqiy, siyosiy va tijoraviy asoslarga ega.\n" +
                "Huquqiy asoslar:\n" +
                "Kiberxavfsizlikning huquqiy asoslariga Internetda va boshqa tarmoq tuzatishlarda qo'llaniluvchi dasturlar va hizmatlar, shu jumladan, ma'lumotlarni muhofaza qilish, himoyalash, o'zgartirish, bekor qilish, kuzatish, bir-biriga ulanish vaqtida tarjima qilish uchun shartnoma (foydalanish shartlari) bor.\n" +
                "Huquqiy qonunlar ham kiberxavfsizlikka e'tibor qaratadilar. Misol uchun, qonunlarda kiberxavfsizlik qonuni (Cybersecurity Act), shaxsiy ma'lumotlarni muhofaza qilish to'g'risidagi qonunlar (Privacy Act) va tarmoqqa kirish to'g'risida qonunlar (Computer Fraud and Abuse Act) mavjud.\n" +
                "Siyosiy asoslar:\n" +
                "Kiberxavfsizlik muhim siyosiy masalalarga aylanadi. Davlatlar, qo'shma tarmoqlar va boshqa tashkilotlar kiberxavfsizlikni tartibga solish uchun siyosiy muhimati ko'paytirishni davom ettiradilar.\n" +
                "Xalqaro tashkilotlar, shu jumladan, Qo'shma Shtatlarning Mustaqil Tizimlar Tuzatish tashkiloti (ITU) va Xalqaro Atom Energiya Agentligi (IAEA), kiberxavfsizlik masalalariga e'tibor qaratish uchun dastlabki tavsiyalarni taklif etdilar.\n" +
                "Tijoraviy asoslar:\n" +
                "Kiberxavfsizlik, tijorat tarmoqlarini va tijorat faoliyatini ko'paytiradi. Tijorat tarmoqlari va tijorat institutlari kiberxavfsizlikni ta'minlash uchun xavfsizlik usullarini joriy etadilar.\n" +
                "Kiberxavfsizlik siyosiy qarorlarga, tijoraviy faoliyatga, tashkilotlar va kompaniyalar faoliyatiga ta'sir qiladi. Kiberxavfsizlikga o'z hissangizni qo'shing va xavfsizlikni ta'minlash uchun tadbirlarni olib borishda qatnashing.\n" +
                "Kiberxavfsizlikning huquqiy, siyosiy va tijoraviy asoslari kiberxavfsizlikning o'zining o'rnini ta'minlaydi va kiberxavfsizlikning jamiyat uchun qanday muhim masala ekanligini ko'rsatadi."),
        QoshimchaModel(R.drawable.tushunchalar, "Kiberxavfsizlik sohasidagi huquqiy vaziyat", "Kiberxavfsizlik sohasidagi huquqiy vaziyat, har bir davlatning xususiy huquq va qonuniyati bilan bog'liqdir. Kiberxavfsizlik, xususiy axborot ma'lumotlar va hukmronlik tizimlariga kirish, hujum yoki o'zgartirish orqali yagona yoki ko'p foydalanuvchilarga zarar yetkazishga qaratilgan huquqiy javobgarlikka ega bo'lishni anglatadi.\n" +
                "Har bir mamlakat, kiberxavfsizlikga qarshi qo'llaniladigan huquqiy asoslar va tizimlarni taqdim etadi. Bu asoslar odatda, kiberxavfsizlikni oldini olish, ma'lumotlarni qayta ishlash va ta'minlash, hujumlarni aniqlash va bu hujumlarni bartaraf qilish kabi vazifalarni o'z ichiga oladi.\n" +
                "Kiberxavfsizlik sohasidagi huquqiy vaziyat, umumiy ravishda, xususiy axborot ma'lumotlari, bank ma'lumotlari va hukumat tizimlariga hujum qilishga qarshi qo'llaniladigan qonunlar kabi qonuniy tizimlar, tartib va qo'llanmalarni taqdim etadi. Bu qonuniy tizimlar odatda, hujumlarga qarshi qo'llaniladigan xavfsizlik protokollari, qayta tiklashlar va to'g'ridan-to'g'ri hujumlar kabi turli turlarda kiberxavfsizlikning qayta tiklanishini o'z ichiga oladi.\n" +
                "Bundan tashqari, kiberxavfsizlik sohasida har bir mamlakatning tashqi xavfsizlik siyosati va xalqaro hamjamiyat tizimlari mavjud. Bu tizimlar, tashqi xavfsizlik hujjatlari va shartnomalar, maxsus xavfsizlik yozuvlari va anjumanlar kabi ko'plab ko'rsatkichlarga asoslanadi.\n" +
                "Kiberxavfsizlik sohasidagi huquqiy vaziyat, hozirgi kunda kattalashtirilmoqda va uning muhim ahamiyati kuzatilmoqda.")
    )

    val arrayqoida:ArrayList<QoshimchaModel> = arrayListOf(
        QoshimchaModel(R.drawable.qoidalar2,"Maxfiylik", "Maxfiylik (Privacy) insonning shaxsiy hayoti va axloqi erkinliklarini himoya qilish imkonini taʼminlash uchun jamiyatda amalga oshirilgan qoʼllanmalardan biridir. Bunda kishining shaxsiy ma'lumotlari (ismi, manzili, tugʼilgan sana, telefon raqami, elektron pochta manzili, xarid qilgan mahsulotlari, xizmatlar, tarixi va h.k.) himoya qilinishi kerak.\n" +
                "Maxfiylik, internet va mobil kommunikatsiyalarni baholashda muhim bir koʼrsatkichdir. Shaxsiy ma'lumotlar onlayn platformalarda yoki telefonda saqlanishi bilan, uning himoyalashini taʼminlash uchun zarur boʼlgan usullarni oʼrganishni talab etadi.\n" +
                "Maxfiylik, barcha insonlarning birinchiligidir va unda yoshlar, oilalar, kasbiy tashkilotlar, huquqiy shaxslar, xizmat koʼrsatuvchilari va h.k. ham qatnashadi. Bugungi kunda internetda foydalanuvchilar va shaxsiy ma'lumotlarni saqlash boʼyicha qoʼllanuvchilar tomonidan maxfiylik qoidalari aniqlovchi shaklda taqdim etiladi.\n" +
                "Maxfiylikning boshqa shakllari shaxsiy hayotning amaliy qismini hisobga olish, tibbiy xizmatlar, yuridik masalalar va h.k. kabi shaxsiy axloqiy tajribani yaxshilashga yoʼnaltirilgan.\n" +
                "Shuningdek, barcha mamlakatlarda maxfiylik huquqi mavjud boʼlib, insonlarning shaxsiy ma'lumotlarini xavfsiz saqlash va ularga nomaʼlum xodimlar tomonidan kirishga qarshi qoʼllanuvchilar taʼminlash uchun maxfiylik huquqi maxsus tizimlarda koʼrsatiladi."),
        QoshimchaModel(R.drawable.qoidalar2,"Kimlik tekshiruvi", "Kimlik to'g'rilama, bir foydalanuvchining haqiqiy kimligini to'g'rilash uchun tuzilgan ish yoki operatsiyalardir. Bu, bir kishining kendisini tanishtirish uchun sunduğu ma'lumotlarning haqiqiyligini kontrol etmek uchun ishlatiladigan bir usuldir. Kimlik to'g'rilama, ko'p turli xil tarzda amalga oshirilishi mumkin, masalan, bir foydalanuvchining bir parola yoki parolga kirishi yoki bir biyometrik xususiyat yaratish (masalan, barmoq izi yoki yuz tanıma) kimligini to'g'rilash kabi. Kimlik to'g'rilama, ayniqsa finansal işlemler gibi hassas faoliyatlerde, bilgi xavfsizligi va maxfiyligini ta'minlash uchun son derece muhimdir."),
        QoshimchaModel(R.drawable.qoidalar2,"Xavfsiz tarmoqlar", "Xavfsiz tarmoqlar yuqori darajada himoya qo'llanadigan tarmoqlardir. Bu tarmoqlar hassas ma'lumotlar yuborish yoki saqlash kerak bo'lgan holatlarda qo'llaniladi. Xavfsiz tarmoqlar a'lochilar trafikni shifrlash, kirish nazoratini bajarish va boshqa xavfsizlik qo'llanmalari orqali ma'lumotlarning xavfsizligini ta'minlashga harakat qiladi. Ayrıca, ağa kirish uchun tasdiqlash kerak bo'ladi va bu hammasi nohimmat kirishni oldini olishga yordam beradi. Xavfsiz tarmoqlar kompaniyalar, hukumat tashkilotlari va boshqa tashkilotlar ma'lumotlarining xavfsizligini ta'minlash uchun keng tarqalgan qo'llanma hisoblanadi."),
        QoshimchaModel(R.drawable.qoidalar2,"Malware ta'qiqlash", "Malware ta'qiqlash, bir tizimni yoki kompyuterni xavfsizlik oqimiga qarshi himoya qilish uchun foydalaniladigan tizim yoki dastur hisoblanadi. Malware ta'qiqlash dasturlari kompyuterni viruslar, trojanlar, qo'llanma portallari va boshqa kuchli malware'ga qarshi himoya qilish uchun yaratilgan. Bu dasturlar tizimni xavfsizlik boshqaruvini o'z ichiga oladi va kuchli antimalware modullari yordamida foydalanuvchilarning tizimlarida yoki tarmoqida yuzaga kelishi mumkin bo'lgan xavfsizlik ochiqchalaridan himoya qilishga yordam beradi. Malware ta'qiqlash dasturlari shifrlangan trafikni ochiqlashtirishi, antivirussiz foydalanuvchilarning xavfsizlik risklarini yuritishini kamaytirishi, kuchli nusxalar o'rnatishini aniqlashga yordam berishi va hokazo kabi kuchli funktsiyalarga ega bo'lishi mumkin. Bu dasturlar Windows, Mac va Linux tizimlarida mavjud bo'lib, kompyuterning xavfsizligini ta'minlashda muhim ahamiyatga ega."),
        QoshimchaModel(R.drawable.qoidalar2,"Kuzatish va qidiruv", "Kuzatish va qidiruv, biror narsani topish uchun qilinadigan amallardir. Kiberxavfsizlik sohasida, kuzatish va qidiruv foydalanuvchilarning faoliyati uchun muhimdir. Bu, tarmoq xavfsizligini ta'minlash, muhim ma'lumotlarni himoya qilish va xavfsizlikni ta'minlash uchun amalga oshirilgan jarayonlardan faqat bir nechasi.\n" +
                "Kuzatish, aslida, tarmoqni yo'qotmagan holda o'tkaziladigan amaldir. Bu amal orqali, tarmoqdagi trafikni kuzatib boriladi va xavfsizlik agentlari tomonidan muvofiqlik yuzaga keltirilganda yoki zararli faoliyat kuzatish jarayonlari aniqlanganida, zararli faoliyatni to'xtatish uchun kerakli imkoniyatlarni o'z ichiga oladi.\n" +
                "Qidiruv esa, kerakli ma'lumotlarni topish uchun amalga oshiriladi. Bu odatda, tarmoqdagi fayllarni va tuzatishlarini qidiruv va aniqlash uchun foydalaniladi. Kiberxavfsizlik sohasida, qidiruv kerakli malumotlarni topish, zararli fayllarni aniqlash va o'chirish, va hujjatlar, e-pochtalarni yoki yagona xususiyatga ega bo'lgan turli tarmoq elementlarini izlash uchun foydalaniladi.\n" +
                "Kuzatish va qidiruv, kiberxavfsizlik sohasida tarmoq xavfsizligini ta'minlash uchun muhim asoslar hisoblanadi va foydalanuvchilarga tarmoqdagi faoliyatlarini kuzatish va kerakli ma'lumotlarni qidirish imkonini beradi."),
        QoshimchaModel(R.drawable.qoidalar2,"Internet tarmoqlarining nazorati", "Internet tarmoqlarining nazorati, Internet-ga kiruvchi trafikni kuzatish va tekshirish yordamida tarmoq xavfsizligini taʼminlashni ifodalovchi amaldir. Bu tarmoq xavfsizligi sohasidagi muhim konseptlardan biridir.\n" +
                "Internet tarmoqlarining nazorati, tarmoq xavfsizligi muhofazasi uchun koʻrsatiladigan faoliyatlar toʻplamidir. Bu nazorat tarmoq tuzilmasi, tarmoqni boshqarish va xavfsizligi taʼminlash uchun zarur boʻlgan boshqa tadbirlarni oʻz ichiga oladi.\n" +
                "Nazorat jarayoni, odatda, tarmoqni qayta tuzatish va nazorat qilish uchun avtomatlashtirilgan vositalar va muhokama vositalari yordamida bajariladi. Tarmoq nazorati, xavfsizlik tizimlari, himoyalash vositalari, tarmoqni oʻzgartirishlaridan ham foydalanish yordamida amalga oshiriladi.\n" +
                "Internet tarmoqlarining nazorati, ayrim xususiyatlarga ega boʻlgan tarmoqlar uchun muhimdir, masalan, korporativ tarmoqlar, dasturiy taʼminot tarmoqlari va boshqa yuqori xavfsizlik talablariga ega boʻlgan tarmoqlar. Shuningdek, xususiy tarmoqlar va tarqatilgan tarmoqlar uchun ham nazorat talab qilinishi mumkin."),
        QoshimchaModel(R.drawable.qoidalar2,"Xavfsizlik ta'limi", "Kiberxavfsizlik ta'limi, bir kishining kiberxavfsizlik bilimini o'rganishi va xavfsizlikni oshirish uchun xizmat qilishni o'rganishni o'z ichiga oladi. Bu, hukumatlar, korporatsiyalar va boshqa tashkilotlar kabi kiberxavfsizlik risklari bilan yuzlashgan barcha insonlar uchun muhimdir.\n" +
                "Kiberxavfsizlik ta'limi, kiberxavfsizlikning qanday ishlaydi va uni oldini olish uchun qanday usullarni qo'llashni o'rganishni o'z ichiga oladi. Bu, zararli kodlarni tahlil qilish, tarmoq xavfsizligi, ma'lumotlar xavfsizligi, ma'lumotlarni himoya qilish va xavfsizlikni ta'minlash uchun boshqa ko'plab masalalarni o'z ichiga oladi.\n" +
                "Kiberxavfsizlik ta'limi dasturlarini o'rganish, tahlil qilish, zararli kodlarni aniqlash va ularni yo'q qilish, ma'lumotlarni himoya qilish va xavfsizlikni ta'minlash uchun boshqa ko'plab texnologiyalardan foydalanishni o'rganishni o'z ichiga oladi. Bu tajriba olish uchun kiberxavfsizlik kurslari, veb-saytlarda onlayn o'quv dasturlari, xalqaro sertifikatli sertifikat dasturlari kabi ko'plab resurslar mavjud."),
        QoshimchaModel(R.drawable.qoidalar2,"Xavfsizlik hukmiyatlari", "Xavfsizlik hukmiyatlari, bir kishi yoki tashkilotning kiberxavfsizlikni buzish yoki kiberjinoiyatlar qilish uchun qonunchilik qoidalari va tartiblari bo'yicha jazolashga duch keldi. Kiberjinoiyatlarning keng ko'p turlari bor va ularga oid bir nechta jinoyatlar qonunlar bilan nazarda tutiladi. Kiberjinoiyatlar o'z ichiga salbiy tarmoq sohasidagi narsalarni nusxalash, internet saytlariga zararli dasturlar joylash va o'zgartirish, shaxsiy ma'lumotlarni nusxalash, faqat bu bilan cheksiz ro'yxat ko'rsatiladi.\n" +
                "Kiberjinoiyatlar jazolashiga doir xizmatlar va qonunlar har bir mamlakatda farqli bo'lishi mumkin. Shunga qarab, kiberxavfsizlik jinoyatlari to'g'risida hukmiy jazolar turli xil bo'lishi mumkin va ularga yuqori muddatli qamrovli jazo to'g'risida ko'rsatmalarni taqdim etish mumkin.\n" +
                "Qonunlar kiberjinoiyatlarning keng turlariga ta'sir qilishi uchun yanada ko'proq tarkibiy va zamonaviy holatga moslashtirilgan. Bunday qonunlar ma'lumotlarni himoya qilish, boshqa insonlarga xavfsizlik ta'minlash va xavfli jinoiyatlarni oldini olishga qaratilgan.\n" +
                "Bir qancha dunyodagi mamlakatlar kiberxavfsizlik jinoyatlariga doir qonunlarini yanada kuchaytirib borishgan. Bu qonunlar jazo to'g'risida tushuntirish, jazolash va muhofaza qilish davomida qonunlar o'zgarishi kabi xolatlar uchun yanada o'zgartirilishi mumkin."),
        QoshimchaModel(R.drawable.qoidalar2,"Kiberxavfsizlik siyosati", "Kiberxavfsizlik siyosati, bir mamlakat yoki tashkilotning kiberxavfsizlikka qarshi kurashish uchun o'zining o'zaro kelishuvlarini, qonuniy va siyosiy qarorlarini joriy qiladigan bir strategiyadur. Bu siyosat tashkil etishda, qonunlar va siyosiy usullar, tizimlar va qurilmalar, kiberxavfsizlikni o'rganuvchi va o'qituvchi materiallar, amaliy mashg'ulotlar, kiberxavfsizlikni aniqlash va to'g'rilash usullari va ko'plab boshqa chora-tadbirlar jamlanadi.\n" +
                "Kiberxavfsizlik siyosati maqsadi, bir mamlakat yoki tashkilotni kiberxavfsizlikdan himoya qilish uchun o'zining iqtisodiy, siyosiy, ijobiy va xavfsizlik xizmatlarini o'zlashtirishni o'z ichiga oladi. Bu siyosat orqali, bir mamlakat yoki tashkilot faoliyati uchun zararli kiber faoliyatlarning kuzatishini, aniqlashini va ta'qiqlanishini, xavfsizlik masalalari bilan shug'ullanuvchilarni xavfsizlik sohasida o'qitish va bilimlarni oshirishni tashkil etishni o'z ichiga oladi.\n" +
                "Kiberxavfsizlik siyosati qonun va nizomlar, siyosiy usullar, kiberxavfsizlikni o'rganuvchi va o'qituvchi materiallar, tizimlar va qurilmalar, kiberxavfsizlikni aniqlash va to'g'rilash usullari va ko'plab boshqa chora-tadbirlar jamlanadi. Siyosat orqali o'zining maqsad va vazifalariga muvofiq kiberxavfsizlikni kamaytirish uchun kerakli qadamlar atiladi.\n" +
                "Kiberxavfsizlik siyosati aholining hayoti va xavfsizlikni ta'minlashning yirik o'rinini egallaydi. Bu siyosat to'g'risida ko'p mamlakatlarda kiberxavfsizlikni qo'llab-quvvatlashni oshirish maqsadida kiberxavfsizlik vazirliklari va tashkilotlari tashkil etilgan. Shu kabi vazirlik va tashkilotlar, xalqaro standartlar asosida kiberxavfsizlikni nazorat qilish va uni ta'minlash uchun qabul qilingan huquqiy va siyosiy hujjatlarga muvofiq harakat qilishlarini ta'minlaydi."),
        QoshimchaModel(R.drawable.qoidalar2,"Ma'lumotlarni saqlash va muhofaza qilish", "Ma'lumotlarni saqlash va muhofaza qilish, kiberxavfsizlikning asosiy qismlaridan biridir va shaxsiy ma'lumotlar, korporativ ma'lumotlar, dasturlar va boshqa mahsulotlar, tarmoqlar va hokazo kabi kritik resurslarni qamrab oladi. Bu sababli, kiberxavfsizlikning muhim tizimlaridan biri ham ma'lumotlarni saqlash va muhofaza qilishdir.\n" +
                "Ma'lumotlarni saqlash va muhofaza qilishga oid asosiy xizmatlar quyidagilardir:\n" +
                "Ma'lumotlarning shifrlanishi: Shifrlash, ma'lumotlarni noma'lum shaxslarning o'qishiga qarshi himoya qilish uchun ularni maxfiy holatda saqlash imkonini beradi.\n" +
                "Kuzatish va ma'lumotni qidiruvchi mexanizmlar: Bu, tarmoq xavfsizligi tizimlariga kiruvchi hamma tashqi va ichki kuzatuv va qidiruvlar uchun muhimdir.\n" +
                "Ma'lumotlar bazalarini himoya qilish: Ma'lumotlar bazasi, biznes yoki tashkilotning asosiy ma'lumotlarini o'z ichiga oladi, shuning uchun ularning himoyalash va xavfsizligi juda muhimdir.\n" +
                "Dasturlarning xavfsizligi: Dasturlar, xususan, korporativ tizimlar uchun ishlab chiqilgan dasturlar xavfsizlik tarmog'i sifatida xizmat qiladi. Dasturlarning xavfsizligi, ma'lumotlarning himoyalashiga qarshi yagona tizim emas, balki har bir dastur tizimining xavfsizligini ta'minlashning muhim qismidir.\n" +
                "Ma'lumotlar bazasiga kirishni cheklash: Bu, ma'lumotlar bazasiga kirishni cheklash, shaxsiy ma'lumotlarga qarshi himoya ta'minlash va korporativ ta'sirchan ma'lumotlarni muhofaza qilish uchun ma'lumotlarning faqatgina ruxsatsiz kirishidan saqlashga qaratilgan tizimdir.\n" +
                "Ma'lumotlarni saqlash va muhofaza qilish, tijorat, salbiy sayoxat va inson huquqlari tomonidan talab qilingan bo'lgani uchun, kiberxavfsizlik siyosati va huquqiyatining muhim tizimlari hisoblanadi."),
    )

    val arraymalumot:ArrayList<QoshimchaModel> = arrayListOf(
        QoshimchaModel(R.drawable.malumotlar, "Wireshark", "Wireshark, tarmoq analizi va tarmoq kommunikatsiyasini nazorat qilish uchun bepul va ochiq manba dasturdir. Ushbu dastur foydalanuvchi tarmoqdagi trafikni ko'rishga imkon beradi, shuningdek, protokol paketlarini analiz qilishga va tarmoqdagi muammolarni aniqlashga yordam beradi.\n" +
                "Wireshark, tarmoqdagi bir qancha protokollarni qo'llash orqali tarmoqdagi bir nechta muammo va xatoliklarni aniqlash imkoniyatini beradi. Dastur aynan bir tarmoqning har bir qismidagi xatoliklarni aniqlash uchun ko'p xil analiz qilish vositalarini taqdim etadi.\n" +
                "Bundan tashqari, Wireshark foydalanuvchilarga tarmoqdagi har qanday bir ko'rsatkichni yoritish uchun bir nechta statistik ma'lumotlarni taqdim etadi. Shular orasida qandaydir protokol paketlarining miqdori, boshqa qurilmalar bilan ulanish va tarmoqdagi portlarning istifodadan o'tkazilishi kabi ma'lumotlarni o'z ichiga oladi.\n" +
                "Wireshark o'rnatilgan tarmoqni muhofaza qilish va xavfsizligini ta'minlashda ham juda muhim dasturlardan biridir. Dastur orqali foydalanuvchilar tarmoqdagi qo'shimcha oqlar yoki tarmoqga ulanishga harakat qilayotgan yomon niyatli foydalanuvchilarni aniqlashlari mumkin bo'ladi."),
        QoshimchaModel(R.drawable.malumotlar, "Nmap", "Nmap tarmoq skaneri, yangi tarmoqni o'rganish va ushbu tarmoqning portlarini skan qilish uchun qo'llaniladigan bepul, ochiq manba. Nmap xususiyatlari, tarmoqlarni skan qilish, tarmoq vositalarini va ularning xususiyatlarini aniqlashga imkon beradi. Bu dastur, portlarni, tarmoq o'zaro aloqalarini va shaxsiy tarmoq vositalarini aniqlashga yordam beradi. Bular quyidagi ko'rsatmalarga ega:\n" +
                "Bepul va ochiq manba: Nmap, ochiq manba xususiyati bilan ishlaydi, shuning uchun ishlatilishi bepuldir.\n" +
                "Har qanday tuzilishni skan qilish: Nmap, bir nechta tuzilishlar, masalan, Windows, Linux, va Mac OS X kabi, tarmoqlariga skan qila oladi.\n" +
                "Port skaneri: Nmap, tarmoqdagi xizmat portlarini aniqlashga yordam beradi. Bular faqat ochiq portlarni emas, balki yopiq portlarni ham aniqlashga imkon beradi.\n" +
                "Skan turli: Nmap, yangi tarmoqni o'rganish uchun bir nechta skan turini taqdim etadi. Masalan, TCP SYN skaner, TCP Connect skaner va UDP skaner.\n" +
                "Xususiyatlar: Nmap, tarmoqdagi vositalarning xususiyatlarini ham aniqlaydi, masalan, tarmoqni to'liq vaqti orqali aniqlash, IP manzillari, tarmoq nomlari va boshqalar.\n" +
                "Nmap o'zini tarmoq xavfsizligi sinfi, tuzilish topish va tarmoq ma'lumotlarini tahlil qilish uchun juda foydali dastur sifatida ko'rsatadi."),
        QoshimchaModel(R.drawable.malumotlar, "Metasploit", "Metasploit, tarmoq xavfsizligini tekshirish va unga hujjatlarni sinash uchun o'rnatilgan avtomatlashtirilgan bir pen-test platformasidir. Bu dastur, xavfsizlik mutaxassislarining tarmoqda xavfsizlikni tekshirish, xavfsizlik uchun sinovdan o'tish (pen-test), xavfsizlik holatida imkoniyatlar va mahsulotlardan foydalanish, tuzilgan xavfsizlik holatlarini tasdiq etish va har qanday xavfsizlik muammolari bilan bog'liq masalalarni hal qilishda yordam beradi.\n" +
                "Metasploit, bir qator modullarni (fayllarni, exploit'larni, bypass qilish vositalarini, to'g'ridan-to'g'ri shell komandalari va boshqa narsalarni) qamrab olish orqali foydalanuvchi tomonidan o'zgartirilgan skriptni ijro etadi. Metasploit keng xavfsizlik loyihasi jamiyatining tomonidan yaratilgan va mustaqil foydalanuvchilar kiritish uchun ochiq manba sifatida mavjud.\n" +
                "Metasploit yordamida foydalanuvchilar, tarmoqda xavfsizlikni tekshirish, tarmoqda xavfsizlik sinovlari o'tkazish, xavfsizlik holatlarida imkoniyatlar va mahsulotlardan foydalanish, sinovlarni natijalari va har qanday xavfsizlik muammolarini aniqlash uchun kerakli vositalarga ega bo'ladi."),
        QoshimchaModel(R.drawable.malumotlar, "TrueCrypt", "TrueCrypt, ma'lumotlar va fayllarni shifrlash uchun ochiq manba kodi bilan yaratilgan xavfsizlik dasturidir. Bu dastur orqali, fayllarni shifrlash va de-shifrlash uchun maxsus shifrlash algoritmlaridan foydalaniladi. TrueCrypt dasturi, Windows, MacOS va Linux kabi ko'plab operatsion tizimlarida ishlaydi.\n" +
                "TrueCrypt, xavfsizlik sohasida foydali bo'lgan bir nechta funksiyalarga ega. Ushbu dastur orqali shifrlangan ma'lumot va fayllarni o'qish, yozish, kopyalash va ko'chirish mumkin. Shuningdek, TrueCrypt, shifrlangan fayl yoki ma'lumotlar to'plamlari uchun o'ziga xos yorliqlar yaratish imkonini taqdim etadi.\n" +
                "TrueCrypt, uzluksizlik uchun parol, kod va berilganlik yoki kalendar kabi ko'nikmalar ishlatadi. Ushbu ko'nikmalar shifrlangan fayllarga kirish imkonini ta'minlash uchun foydalaniladi. Shuningdek, TrueCrypt, shifrlangan fayl yoki ma'lumotlar to'plamlari uchun o'ziga xos yorliqlar yaratish imkonini taqdim etadi.\n" +
                "Hozircha, TrueCrypt yaratuvchilari dasturning ishlab chiqarilishidan so'ng dastur yana yangilanmagan. Ammo shu bilan birga, TrueCrypt keng ko'lamli bir jamoa tomonidan ishlatiladi va ko'p xavfsizlik mutaxassislarining tomonidan tavsiya etiladi."),
        QoshimchaModel(R.drawable.malumotlar, "ClamAV", "ClamAV, xavfsizlik dasturi sifatida, Unix va Windows xavfsizlik tizimlari uchun muayyan viruslarni va zararli dasturlarni aniqlash va o'chirishga yordam beradi. Ushbu dastur ochiq manba kodi asosida ishlab chiqilgan bo'lib, shuningdek, ingichka yozilgan bo'lib, ma'lumotlar tarmog'i xavfsizligini ta'minlash uchun serverlar, elektron pochta xizmatlarida, web resurslarda va boshqa tarmoqlarda foydalaniladi.\n" +
                "ClamAV dasturi viruslarni imzo (signature) bilan aniqlaydi, yani, virusning tavsifi, shakli va kelgusi ma'lumotlar bilan solishtirib, viruslarni aniqlaydi. ClamAV yozilgan bo'lib, ko'p distributivlarida tayyorlangan va undan foydalanilishi eng sodda viruslarni aniqlash imkoniyatini beradi. Ushbu dastur shaxsiy xavfsizlikni ta'minlashda, serverlarda va tarmoqda xavfsizlikni ta'minlashda, elektron pochta xizmatlarida, web saytlarda, foydalanuvchi qurilmalarida va hokazo ko'p tashkilotlar va tarmoqlarda foydalaniladi."),
        QoshimchaModel(R.drawable.malumotlar, "Snort", "Snort, tarmoq xavfsizligini ta'minlash uchun katta hissa qiladigan xavfsizlik tizimi dasturi hisoblanadi. Bu IPS (intrusion prevention system) dasturi, tarmoq xavfsizligini ta'minlash uchun xavfsizlik tahlilini bajaradi va xavfsizlik hadisalari yuz berganda ishga tushiriladi.\n" +
                "Snort dasturi foydalanuvchilar tomonidan xavfsizlik tahlili uchun ko'p yo'nalishlarda qo'llaniladi, masalan, tarmoqdagi trafikni analiz qilish, to'g'ridan-to'g'ri tahlil qilish yoki xavfsizlikni ta'minlash uchun cheklovlarni yaratish. Snort foydalanuvchilarga o'zgaruvchan qoidalarni belgilash imkoniyatini taqdim etadi va xavfsizlikni ta'minlash uchun avtomatik tarzda tartibga soladi.\n" +
                "Snort dasturi ochiq manba kodi bilan ta'minlangan, bu esa foydalanuvchilar tomonidan dasturda o'zgartirishlar kiritish imkonini taqdim etadi va foydalanuvchilarning o'z mahsulotlarini yaratishiga imkon beradi. Bundan tashqari, Snort dasturi ko'plab ko'rsatkichlar bilan ta'minlangan, shuningdek, o'rnatilgan to'lovli dasturlarga qarshi cheklovlar qo'yish uchun imkoniyatlar mavjud.\n" +
                "Barcha xususiyatlari bilan Snort tarmoq xavfsizligini ta'minlash uchun juda foydali dastur hisoblanadi va tarmoq xavfsizligini ta'minlashda katta ahamiyatga ega."),
    )

    val malumot:String = "Amaliyot, teorik bilimlarni amalda qo'llashga qaratilgan sinov dasturlarini o'z ichiga oladi. Kiberxavfsizlik sohasida ham bu holat hamda ishlaydigan dasturlar uchun amaliyot juda muhimdir.\n" +
            "Amaliyot qilish uchun bir necha usullar mavjud. Misol uchun, siz o'zingizning kompyuteringizda xavfsizlikni oshirishingiz kerak. Bu uchun, siz o'z dasturlaringizni va operatsion tizimingizni yangilab, yozilgan viruslar va malware lar to'g'risida ochiq bo'lgan yangilanishlarni kuzatishingiz kerak. Shuningdek, siz internet orqali yuborilayotgan ma'lumotlarni nazorat qilish uchun uchun tarjima dasturlari, virtual xizmatlar va VPN yordamida xavfsizlikni oshirishingiz mumkin.\n" +
            "Kiberxavfsizlik sohasidagi amaliyot odatda o'z-o'zini sinov qilish, tarmoq skanerlari yordamida tarmoqni tekshirish, pen-testlar, xavfsizlik tahlili va boshqa kiberxavfsizlik masalalari bilan shug'ullanishni o'z ichiga oladi. Bu usullar hamda ularning dasturlari o'rganish va amaliyotda qo'llash, kiberxavfsizlik sohasida muvaffaqiyatli bo'lishingiz uchun muhimdir."
}